project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!projects"
  resources:
    - projects/dsan-5000/_site
    - projects/dsan-5100/_site

website:
  title: "Portfolio"
  favicon: "images/gu-logo.png"
  navbar:
    background: "#d6ccc2"
    toggle-position: right
    left:
      - href: index.qmd
        text: Home

      - text: "Projects"
        menu: 
          - text: NYC Schools, Socioeconomics & Success - Fall 2024
            href: projects/dsan-5000/_site/index.html
          - text: Statistical Analysis of Airbnb - Fall 2024
            href: projects/dsan-5100/_site/index.html
          - text: HIV/AIDS Through Visualization - Spring 2025
            href: projects/dsan-5200/_site/index.html
          - text: Risk Factors for Aid Worker Attacks - Spring 2025
            href: projects/scholarship/_site/index.html


format:
  html:
    theme: 
      - lux
      - styles/custom.scss
    toc: true



