project:
  type: website
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!projects"
  resources:
    - projects/dsan-5000/_site

website:
  title: "Portfolio"
  favicon: "images/gu-logo.png"
  navbar:
    left:
      - href: index.qmd
        text: Home

      - text: "Projects"
        menu: 
          - text: NYC Schools, Socioeconomics & Success - Fall 2024
            href: projects/dsan-5000/_site/index.html
          - text: Statistical Analysis of Airbnb - Fall 2024
            href: projects/dsan-5100/_site/index.html

format:
  html:
    theme: cosmo
    toc: true



